### ISSUE TITLE
[Docs] Docs Related Issues Altogether

### ISSUE THREAD

**Issue by StarTrooper08** [r-devel/r-dev-env#119]
Work in Progress PR

https://github.com/r-devel/r-dev-env/pull/118

Changes  made

- [x] Added new section -  Container  Setup #96 #113 
- [x] Updated  Local setup  docs  #99 
- [x] Simplified patchfile  docs #115 
- [x] Renamed  R dev env  to R dev container in  some places(WIP) #97 
- [x] Updated  Codespace Start and Stop docs file  #117 
- [x] #107
- [x] #105
- [x] #97 
- [x] #108 
- [x] #114

**Comment by StarTrooper08** [comment]
Building R file last part which needs multi_r feature docs is remaining.
